version: '3'

services:
  model-api:
    build:
      context: .
      dockerfile: Model_Deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Model_Training/models:/app/models
    environment:
      - MODEL_DIR=/app/models
      - DEFAULT_MODEL=linear_gbm_ensemble
      - PORT=8000
    restart: always

  streamlit-app:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    